default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pagepal_development
  username: postgres
  password: <%= ENV['DEV_DB_PASSWORD'] %> # optional if your local DB has a password
  host: localhost

test:
  <<: *default
  database: pagepal_test
  username: postgres
  password: <%= ENV['TEST_DB_PASSWORD'] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>

cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cache:
  <<: *default
  url: <%=  ENV['DATABASE_URL'] %>
